### ISSUE TITLE
Doesn't seem to be working for me.

### ISSUE THREAD

**Issue by gregma** [3DPrintDemon/Demon_KLIPPER_Essentials#1]
Soval SV07+
Demon_Start_End_Print.cfg (v1.1)
Heat_Soak_Sovol.cfg (v1.1)
Demon_Essentials.cfg (v1.1)

All uploaded to the Configuration Files section in Fluidd

Added:
[include Demon_Essentials.cfg]
[include Demon_Start_End_Print.cfg]
[include Heat_Soak_Sovol.cfg]

To the top of the printer.cfg (just under the [include plr.cfg]
gcode_macro START_PRINT and gcode_macro END_PRINT macros commented out

Using Orca Slicer
Machine G-code start set to:
M104 S0 
M140 S0
PRINT_START EXTRUDER=[first_layer_temperature[initial_extruder]] BED=[first_layer_bed_temperature] HEIGHT=[first_layer_height]

Machine end G-code set to:
PRINT_END

Created a new HOT bed mesh

Sliced a simple object, sent to printer:

In the console, I immediately get:
File opened:clamp_protector_tri_PLA_10m3s.gcode Size:991936
20:52:48 File selected
20:52:48 // Extrude below minimum temp
// See the 'min_extrude_temp' config option for details
20:52:48 !! Extrude below minimum temp

Seems as if most of the macro isn't running at all?  This is my first foray into klipper.  Hopefully I provided enough info.

**Comment by 3DPrintDemon** [comment]
Hi there. Have you commented out the SV07’s own Print_start macro in the printer.cfg? If not this might be the issue.

**Comment by gregma** [comment]
3 minutes before I came here, I indeed noticed that there was a PRINT_START and PRINT_END in the printer.cfg.  I commented out the START_PRINT and END_PRINT wondering why I would be directed to do that when they were named differently.  It was a user error 100%!
