### ISSUE TITLE
PRINT_START - no attribute 'BED'

### ISSUE THREAD

**Issue by LiquidState317** [3DPrintDemon/Demon_KLIPPER_Essentials#3]
So this one is probably me, but everything seems like it should be perfect, I set up all the values and did the bed mesh. I go to print something, it preheats, heatsoaks for 2 minutes, then after it prints the purge line, it throws up this error: 
![Capture](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/94092835/17fc1e40-28b1-4e5a-be79-574612dbcd21)

Know off the top of your head what could be causing this? It seems to be another problem I cant just use ctrl-f for

**Comment by 3DPrintDemon** [comment]
If this is on the Sovol Sv06 or SV07 Klipper screen then its a weird quirk with that system. 
I get it on my SV07 here, it all still works as it should but throws that error for some strange reason, not found the source but the exact same macro works perfectly fine on main branch Klipper on all my other machines. I mention about the errors at the bottom of the instructions text, it can be ignored.
