### ISSUE TITLE
Malformed command error

### ISSUE THREAD

**Issue by cbaugher** [3DPrintDemon/Demon_KLIPPER_Essentials#5]
I'm getting a malformed command error when trying to print the attached file.  I took a brief look at the adaptive PA macro and it looks like it should handle unknown extrusion types.  But apparently not.  This was sliced in Orca 1.9.0.
I can provide more info if needed.

`10:19 AM Malformed command '# _ADAPTIVE_PA TYPE=Skirt'`

[20X20X20_TPU_14m26s.zip](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/files/13979490/20X20X20_TPU_14m26s.zip)

**Comment by 3DPrintDemon** [comment]
Ohh that’s interesting. As you say it should indeed print the skirt as the default filament type PA value. I use orca 1.9.0 myself as you know from before & have printed multiple files with it without seeing that error. 

As I don’t get this error there’s 2 things you could try:

First you could try changing line 88 (online file) of _ADAPTIVE_PA to:
```
{% elif not ext_type in ["Perimeter", "ExternalPerimeter", "InternalInfill", "SolidInfill", "TopSolidInfill"] %}
```
See if that helps out any as maybe its not seeing the not there.

If that doesn’t work you could copy/paste this into the _ADAPTIVE_PA macro at line 87.

Ive not tested it so it might have a mistake in it
```
{% elif ext_type == "Skirt" and apa_vars.skirt > 0 %}
      {% if start_vars.apa_readback_enable == True %}
        RESPOND TYPE=COMMAND MSG="PA change APA setting skirt default {apa_vars.skirt}”
      {% endif %}
        SET_PRESSURE_ADVANCE ADVANCE={apa_vars.skirt}
```


Then add this to the bottom of the TPU block of  _APA_SET at line 184 (online file):
```
 SET_GCODE_VARIABLE MACRO=_APA_VARS VARIABLE=skirt VALUE={start_vars.tpu_pa|float}
```

Then add this to _APA_VARS list between lines 101-108 (online file), don’t replace anything just bump whatever is below down one to make a gap.
```
variable_skirt: 0
```

Note also, while checking I did find infill was using the default value so I’ve updated that.

**Comment by 3DPrintDemon** [comment]
Just tested the macro here as posted & it works as expected for the skirt using an orca file. It chooses the “extrusion not in list option” & sets the PA value correctly to the filament default set in the user_settings file as it should. 
![Image 2024-01-19 at 00 16](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/122202359/e3bc1874-5632-4f31-8b35-8f7ebb960d3c)

**Comment by cbaugher** [comment]
Ok, I'm a dummy.  The problem was that I forgot to remove the comment hash from the role type gcode line in the slicer.  Duh!

It's printing now, although I'm getting a different error when it goes to print the top layer.  I'll have to look at that one tomorrow, as it's too late at night to mess with it now.

You can close this one as a false alarm.  Lol!

**Comment by 3DPrintDemon** [comment]
Ahhh ok, I did see the hash there in your pasted error above, but thought nah can't be. Good you found that issue anyway.
Strange you keep getting all these errors, hopefully the top layer one is another easy fix.

**Comment by 3DPrintDemon** [comment]
> Ok, I'm a dummy. The problem was that I forgot to remove the comment hash from the role type gcode line in the slicer. Duh!
> 
> It's printing now, although I'm getting a different error when it goes to print the top layer. I'll have to look at that one tomorrow, as it's too late at night to mess with it now.
> 
> You can close this one as a false alarm. Lol!

Just fixed the top layer thing. Please update your files.

**Comment by cbaugher** [comment]
Thanks for the top layer fix!  I don't know what it was but it's gone, and the printer is successfully printing now.

**Comment by 3DPrintDemon** [comment]
Cool, you're welcome! Great stuff, glad to hear it & thank you for contributing to help make these macros better!
