### ISSUE TITLE
Unknown Command SET_PIN in Start Print Macro

### ISSUE THREAD

**Issue by Bb06477** [3DPrintDemon/Demon_KLIPPER_Essentials#7]
I'm sure its the result of my own ignorance, but I am having trouble diagnosing a repeating return in the console during the start print macro.

I am assuming its to do with the neopixel lighting. Ive run through the files to make sure my naming of the lights matches the macro naming. Any advice on where to look next? 

"8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
8:00 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:59 AM
Unknown command:"SET_PIN"
7:57 AM
pressure_advance: 0.020000
pressure_advance_smooth_time: 0.040000
7:57 AM
File selected
7:57 AM
File opened:blink_camera_mount_adapter_7m_0.20mm_220C_PLA_ENDER3.gcode Size:345125"

**Comment by 3DPrintDemon** [comment]
Hi! Ok there's an odd one! There's only one use of "SET_PIN" in the start macro & yes its to do with the LED's being brought up to full brightness if enabled "True" in the user settings file.
Please double check starting from line 123 that your macro reads like this:
```
  {% if start_vars.printer_lights == True %}  
    {% if printer["my_led"] != start_vars.printer_lights_print %}
      SET_PIN PIN=my_led VALUE={start_vars.printer_lights_print}
    {% endif %}
  {% endif %}
```
If line 125 is not `SET_PIN PIN=my_led VALUE={start_vars.printer_lights_print}`
this could cause the unknown command warning.

Also you can try setting the option of `variable_printer_lights:` to` False` & see if it goes away. If yes then its to do with the lines I posted above.

Hope that helps.

**Comment by Bb06477** [comment]
You are the best! thank you so much for the response, Originally i had assigned the value or the neopixels to "lights" and decided instead of renaming i would control+F to replace all the "my_led" with "lights" and naturally that changed the lights inside the printer variable to my_led and caused an unknown... so i fixed that and then it still ran the unknown set pin so i went into the printer config and found that i had set them up as neopixels and not as output pin.. resetting them into an output pin config corrected the issue 

just as i suspected, my own ignorance.. thank so much!
